import CoverageDetail from './CoverageDetail.jsx';
import React,{useState} from 'react';
import {Card} from './ui.jsx';
import {num} from '../lib/api.js';
import {exportReportRows} from '../lib/report-csv.js';
export default function CoverageTable({rows,ward=false}) {
  const [selected,setSelected]=useState(null);
  const [q,setQ]=useState(''),[lga,setLga]=useState(''),[coverage,setCoverage]=useState(''),[order,setOrder]=useState('name'),[direction,setDirection]=useState('asc');
  const all=rows.map(r=>({...r,reached:ward?r.units_reached:r.units,expected:ward?r.polling_units:r.units_expected,name:[r.lga,ward?r.ward:''].join(' ')}));
  const filtered=all.filter(r=>(!lga||r.lga===lga)&&r.name.toLowerCase().includes(q.toLowerCase().trim())&&(!coverage||(coverage==='none'?r.reached===0:coverage==='complete'?r.expected>0&&r.reached>=r.expected:r.reached>0&&r.reached<r.expected)));
  filtered.sort((a,b)=>{const value=r=>order==='coverage'?(r.expected>0?r.reached/r.expected:0):order==='remaining'?r.expected-r.reached:order==='promoters'?r.promoters||0:order==='voters'?r.voters||0:order==='projects'?r.projects||0:r.name;const av=value(a),bv=value(b);return(typeof av==='number'?av-bv:av.localeCompare(bv))*(direction==='asc'?1:-1);});
  return <Card title={ward?'Ward totals':'Coverage by Local Government Area'} note={ward?'Coverage counts recognised polling units with registrations.':'Promoter = covered / expected. Expected = total PUs × 10 promoters (4 Senate + 3 HOR + 3 HOA). Covered counts all registered promoters in the LGA, including those awaiting PU allocation.'} bodyClass="">
    <div className="toolbar"><input type="search" aria-label={ward?'Search wards':'Search LGAs'} placeholder="Search" value={q} onChange={e=>setQ(e.target.value)}/>{ward&&<select aria-label="Filter ward LGA" value={lga} onChange={e=>setLga(e.target.value)}><option value="">All LGAs</option>{[...new Set(all.map(r=>r.lga))].sort().map(v=><option key={v}>{v}</option>)}</select>}<select aria-label="Filter coverage" value={coverage} onChange={e=>setCoverage(e.target.value)}><option value="">All coverage</option><option value="none">Not reached</option><option value="partial">Partly covered</option><option value="complete">Fully covered</option></select></div>
    <div className="toolbar"><select aria-label="Order coverage table" value={order} onChange={e=>setOrder(e.target.value)}><option value="name">Name</option><option value="coverage">PU cov %</option><option value="remaining">Unit gap</option>{ward?<><option value="voters">Voters</option><option value="projects">Projects</option></>:<><option value="promoters">Promoter</option><option value="voters">Voters</option></>}</select><select aria-label="Coverage sort direction" value={direction} onChange={e=>setDirection(e.target.value)}><option value="asc">Lowest first</option><option value="desc">Highest first</option></select><button className="btn secondary sm" onClick={()=>exportReportRows(filtered.map(r=>ward?{lga:r.lga,ward:r.ward,pu_cov:`${r.reached}/${r.expected}`,unit_gap:r.expected-r.reached,voters:r.voters??'Not loaded',projects:r.projects,PDP:r.pdp_people??'Not loaded'}:{voters:r.voters??'Not loaded',PDP:r.pdp_people??'Not loaded',lga:r.lga,promoters_covered:r.promoters||0,promoters_expected:r.promoters_expected||0,ward_cov:`${r.wards}/${r.wards_expected}`,pu_cov:`${r.reached}/${r.expected}`}),ward?'kwarax10-ward-totals.csv':'kwarax10-lga-coverage.csv')}>Export</button></div>
    <p className="muted" aria-live="polite">Showing {num(filtered.length)} of {num(all.length)} {ward?'wards':'LGAs'} · PU cov {num(filtered.reduce((s,r)=>s+r.reached,0))} / {num(filtered.reduce((s,r)=>s+r.expected,0))}{!ward&&` · Ward cov ${num(filtered.reduce((s,r)=>s+r.wards,0))} / ${num(filtered.reduce((s,r)=>s+r.wards_expected,0))}`}</p>
    <div className="table-wrap coverage-table-scroll"><table data-native-tools="true"><thead><tr><th>{ward?'LGA / Ward':'LGA'}</th>{!ward&&<><th>Promoter</th><th>Ward cov</th></>}<th>PU cov</th><th>PDP</th>{!ward&&<th>Voters</th>}{ward&&<><th>Unit gap</th><th>Voters</th><th>Projects</th></>}</tr></thead><tbody>{filtered.map(r=><tr key={r.name} className="coverage-clickable-row" tabIndex={0} aria-haspopup="dialog" aria-label={'View details for '+r.name} onClick={()=>setSelected(r)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(r);}}}><td>{r.lga}{ward&&<div>{r.ward}</div>}</td>{!ward&&<><td title="All registered promoters / expected promoters">{num(r.promoters||0)} / {num(r.promoters_expected||0)}</td><td>{num(r.wards)} / {num(r.wards_expected)}</td></>}<td>{num(r.reached)} / {num(r.expected)}</td><td>{(r.pdp_people==null?'Not loaded':num(r.pdp_people))}</td>{!ward&&<td>{r.voters==null?'Not loaded':num(r.voters)}</td>}{ward&&<><td>{num(r.expected-r.reached)}</td><td>{r.voters==null?'Not loaded':num(r.voters)}</td><td>{num(r.projects)}</td></>}</tr>)}</tbody></table></div>
    {selected&&<CoverageDetail row={selected} kind={ward?'ward':'lga'} onClose={()=>setSelected(null)}/>}
  </Card>;
}
